### ISSUE TITLE
error if a json raw string is not compressed

### ISSUE THREAD

**Issue by lilixxs** [Rollingegg/feishu-robot-action#7]
如果传入的 json 字符串没有压缩，就会报错，希望动作里支持传入未压缩的字符串
If the input JSON string is not compressed, an error will occur. The action should support passing in an uncompressed string.

Example: If the following uncompressed JSON string passed in, the action will report an error.
举例：传入以下内容，动作会报错
```json
{
  "content": {
    "post": {
      "zh_cn": {
        "title": "🤖 Github CI/CD 结果",
        "content": [
          [
            {
              "tag": "text",
              "text": "工作流："
            },
            {
              "tag": "text",
              "text": "${{ github.workflow }}"
            }
          ],
          [
            {
              "tag": "text",
              "text": "仓库："
            },
            {
              "tag": "text",
              "text": "${{ github.repository }}"
            }
          ],
          [
            {
              "tag": "text",
              "text": "触发事件："
            },
            {
              "tag": "text",
              "text": "${{ github.event_name }}"
            }
          ],
          [
            {
              "tag": "text",
              "text": "--------------------------"
            }
          ],
          [
            {
              "tag": "text",
              "text": "执行结果"
            },
            {
              "tag": "text",
              "text": "OK-${{ github.action_status }}"
            }
          ]
        ]
      }
    }
  }
}
```

但传入压缩后的 json 字符串，就能正常发送
However, if a compressed JSON string is passed in, it will be sent successfully.
```json
{ "content": { "post": { "zh_cn": { "title": "🤖 Github CI/CD 结果", "content": [ [ { "tag": "text", "text": "工作流：" }, { "tag": "text", "text": "${{ github.workflow }}" } ], [ { "tag": "text", "text": "仓库：" }, { "tag": "text", "text": "${{ github.repository }}" } ], [ { "tag": "text", "text": "触发事件：" }, { "tag": "text", "text": "${{ github.event_name }}" } ], [ { "tag": "text", "text": "--------------------------" } ], [ { "tag": "text", "text": "执行结果" }, { "tag": "text", "text": "OK-${{ github.action_status }}" } ] ] } } }}
```

传入JSON字符串的时候使用了 github action 的变量，相关代码
in my codes, json is generated by following transformation (yaml -> json)
```yaml
- name: prepare messages for feishu sending
  run: |
    echo "
    msg_type: post
    content:
      post:
        zh_cn:
          title: '🤖 Github CI/CD 结果'
          content:
          - - tag: text
              text: '工作流：'
            - tag: text
              text: ${{ github.workflow }}
          - - tag: text
              text: '仓库：'
            - tag: text
              text: ${{ github.repository }}
          - - tag: text
              text: '触发事件：'
            - tag: text
              text: ${{ github.event_name }}
          - - tag: text
              text: '--------------------------'
          - - tag: text
              text: '执行结果'
            - tag: text
              text: 'OK-${{ github.action_status }}'
    " > msg.yaml
    echo msg.yaml

- name: convert msg from yaml to json
  run: |
    # yq -- 将 yaml 文件转换为 json
    wget https://github.com/mikefarah/yq/releases/download/v4.16.2/yq_linux_amd64 \
    && chmod +x yq_linux_amd64 \
    && mv yq_linux_amd64 /usr/local/bin/yq
    yq eval -o json msg.yaml |tee msg.json
    # 将处理好的结果存储到环境变量 MSG_JSON
    echo "MSG_JSON=$(cat msg.json)" >> $GITHUB_ENV

- name: send messages to feishu -- Bot test
  uses: Rollingegg/feishu-robot-action@v1
  with:
    version: 2
    uuid: ${{ secrets.FEISHU_BOT_WEBSOCKET_ENDPOINT }}
    secret: ${{ secrets.FEISHU_BOT_AUTHKEY }}
    json: |
      ${{ env.MSG_JSON }}
```
